import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";

export async function getServerSideProps({
  params,
}: {
  params: { index: string };
}) {
  // 在构建时将接收到 `posts` 参数
  return { props: { params: { index: Number(params.index || "0") } } };
}

const SSRPage: NextPage = ({ params }: any) => {
  const { index } = params;
  const imgList: string[] = [
    "https://qqweb.top/other/xinjiang/391624848545_.pic.jpg",
    "https://qqweb.top/other/xinjiang/411624848635_.pic.jpg",
    "https://qqweb.top/other/xinjiang/431624848636_.pic.jpg",
    "https://qqweb.top/other/xinjiang/341624848545_.pic.jpg",
  ];
  const imgUrl = imgList[index % imgList.length];

  return (
    <div className={styles.container}>
      <Head>
        <title>动态ID页面</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          体验 <a href="https://nextjs.org">动态ID</a>
        </h1>

        <div className={styles.grid}>
          <a className={styles.card}>
            <h2>动态ID：{index} &rarr;</h2>
            <Image src={imgUrl} alt="景色" width={640} height={480} />
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default SSRPage;
