import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Script from "next/script";
import styles from "../../styles/Home.module.css";

export async function getServerSideProps({
  params,
}: {
  params: { dynamicPath: string [] };
}) {
  // 在构建时将接收到 `posts` 参数
  return { props: { params } };
}

const SSRPage: NextPage = ({ params }: any) => {
  const { dynamicPath } = params;

  return (
    <div className={styles.container}>
      <Head>
        <title>动态路径页面</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          服务端获取动态路径数组 <a href="https://nextjs.org">{ dynamicPath }</a>
        </h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
      <Script
        src="https://connect.facebook.net/en_US/sdk.js"
        strategy="lazyOnload"
      />
    </div>
  );
};

export default SSRPage;
