import type { NextPage } from "next";
import { useEffect, useState } from "react";
import axios from "axios";
import Head from "next/head";
import dynamic from "next/dynamic";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const DynamicImage = dynamic(() => import("../component/image"), {
  ssr: false,
});

async function getData() {
  const data = await axios
    .post("/api/getcsrdata")
    .then((res) => {
      return res?.data;
    })
    .catch((err) => ({ serverTime: 0, weekDate: "", hms: "" }));
  return data;
}

const CSRPage: NextPage = () => {
  const [isClientSide, setIsClientSide] = useState(false);

  const [csrInfo, setCSRInfo] = useState({
    serverTime: 0,
    weekDate: "",
    hms: "",
  });

  const { weekDate, hms } = csrInfo;

  useEffect(() => {
    setIsClientSide(true);
    const interval = setInterval(() => {
      getData().then((res) => {
        if (res.code == 200) {
          setCSRInfo(res.data);
        }
      });
    }, 1000);

    return () => {
      clearInterval(interval);
    };
  }, [hms]);

  return (
    <div className={styles.container}>
      <Head>
        <title>CSR测试页面</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          CSR (SSR+CSR)
          <p>two-pass rendering OR import + ssr: false</p>
        </h1>

        <p className={styles.description}>
          <code className={styles.code}>
            nextjs
            并没有完全的csr，此方案为部分csr，也就是这个页面部分代码也会在服务端渲染执行，useEffect
            钩子只会在客户端触发，我们通过 useEffect
            在客户端请求数据更新页面，第二点我们通过使用next.js提供的动态import
            + 禁用SSR{" "}
          </code>
        </p>

        <div className={styles.grid}>
          <a className={styles.card}>
            <h2>{weekDate} &rarr;</h2>
            <p>{hms}</p>
          </a>
          {isClientSide && (
            <a className={styles.card}>
              <DynamicImage />
            </a>
          )}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default CSRPage;
