import type { NextPage } from "next";
import { useEffect, useState } from "react";
import axios from "axios";
import Head from "next/head";
import dynamic from "next/dynamic";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const DynamicImage = dynamic(() => import("../component/image"), {
  ssr: false,
});

async function getData() {
  const data = await axios.post("/api/getcsrdata").then((res) => {
    return res?.data;
  });
  return data;
}

const CSRPage: NextPage = () => {
  const [isClientSide, setIsClientSide] = useState(false);

  const [csrInfo, setCSRInfo] = useState({
    serverTime: 0,
    weekDate: "",
    hms: "",
  });

  const { weekDate, hms } = csrInfo;

  useEffect(() => {
    setIsClientSide(true);
    const interval = setInterval(() => {
      getData().then((res) => {
        if (res.code == 200) {
          setCSRInfo(res.data);
        }
      });
    }, 1000);

    return () => {
      clearInterval(interval);
    };
  }, [hms]);

  return (
    <div className={styles.container}>
      <Head>
        <title>CSR测试页面</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          体验{" "}
          <a href="https://nextjs.org">
            CSR two-pass rendering OR import + ssr: false
          </a>
        </h1>

        <p className={styles.description}>
          当前页面路径 <code className={styles.code}>/csr</code>
        </p>

        <div className={styles.grid}>
          <a className={styles.card}>
            <h2>{weekDate} &rarr;</h2>
            <p>{hms}</p>
          </a>
          {isClientSide && (
            <a className={styles.card}>
              <DynamicImage />
            </a>
          )}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default CSRPage;
