import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import maxImgUrla from "../public/a.jpeg"
import maxImgUrlb from "../public/b.jpeg"

const CSRPage: NextPage = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>CSR测试页面</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        Image
          <p>加载体验</p>
        </h1>
        <p>武汉长江大桥</p>
        <div style={{ position: 'relative',width: 1200, height: 900 }}>
            <Image src={ maxImgUrla } alt="一张图" width={800} height={600} layout="fill" placeholder='blur'  />
        </div>
        <p>新疆库俄铁路</p>
        <div style={{ position: 'relative',width: 1200, height: 900 }}>
            <Image src={ maxImgUrlb } alt="一张图" width={800} height={600} layout="fill" placeholder='blur'  />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default CSRPage;
