import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import docList from "../util/docs";

export async function getStaticProps() {
  const revalidate = 1;
  console.log(`每${revalidate}秒增量更新一次`);

  return {
    props: { docInfo: docList[0] },
    // 开启 ISR，最多每10s重新生成一次页面（在这里可以去拉取最新服务端数据来更新）
    revalidate,
  };
}

const ISRPage: NextPage = ({ docInfo }: any) => {
  const { title, author, content } = docInfo;
  return (
    <div className={styles.container}>
      <Head>
        <title>ISR测试页面</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          ISR（SSG+SSR）<a>基于SSG基础上拓展了增量更新能力</a>
        </h1>

        <p className={styles.description}>
          <code className={styles.code}>
            核心点在于通过getStaticProps获取数据，并在返回的数据中设置revalidate来控制编译更新的
          </code>
        </p>

        <div className={styles.grid}>
          <a className={styles.card}>
            <h2>{title} &rarr;</h2>
            <h3>{author} &rarr;</h3>
            <p>{content}</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default ISRPage;
