import type { NextPage } from "next";
import axios from "axios";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import docList from "../util/docs";

export async function getStaticProps() {
  // 在构建时将接收到 `posts` 参数
  return { props: { docInfo: docList[0] } };
}

const SSGPage: NextPage = ({ docInfo }: any) => {
  const { title, author, content } = docInfo;
  return (
    <div className={styles.container}>
      <Head>
        <title>SSG测试页面</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          体验 <a>SSG</a>
        </h1>

        <p className={styles.description}>
          当前页面路径 <code className={styles.code}>/ssg</code>
        </p>

        <div className={styles.grid}>
          <a className={styles.card}>
            <h2>{title} &rarr;</h2>
            <h3>{author} &rarr;</h3>
            <p>{content}</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default SSGPage;
