import type { NextPage } from "next";
import axios from "axios";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export async function getServerSideProps() {
  // 调用外部 API 获取内容
  const result = await axios
    .post("http://127.0.0.1:3000/api/getssrdata")
    .then((res) => {
      return res?.data;
    });
  const { data } = result;

  // 在构建时将接收到 `posts` 参数
  return { props: { data } };
}

const SSRPage: NextPage = ({ data }) => {
  const { imgTitle, imgUrl } = data;
  return (
    <div className={styles.container}>
      <Head>
        <title>CSR测试页面</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          体验{" "}
          <a href="https://nextjs.org">
            CSR two-pass rendering OR import + ssr: false
          </a>
        </h1>

        <p className={styles.description}>
          当前页面路径 <code className={styles.code}>/csr</code>
        </p>

        <div className={styles.grid}>
          <a className={styles.card}>
            <h2>{imgTitle} &rarr;</h2>
            <Image src={imgUrl} alt={imgTitle} width={256} height={171} />
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default SSRPage;
