import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import docList from "../../util/docs";

export async function getStaticPaths() {
  // 返回该动态路由可能会渲染的页面数据，比如 params.id
  const paths = [
    {
      params: { id: "0" },
    },
    {
      params: { id: "1" },
    },
    {
      params: { id: "2" },
    },
  ];
  return {
    paths,
    // 命中尚未生成静态页面的路由直接返回 404 页面
    fallback: false,
  };
}

export async function getStaticProps({ params }: { params: { id: string } }) {
  return { props: { docInfo: docList[Number(params.id || "0")] } };
}

const SSGPage: NextPage = ({ docInfo }: any) => {
  const { title, author, content } = docInfo;
  return (
    <div className={styles.container}>
      <Head>
        <title>SSG测试页面</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          体验 <a>SSG</a>
        </h1>

        <p className={styles.description}>
          当前页面路径 <code className={styles.code}>/ssg</code>
        </p>

        <div className={styles.grid}>
          <a className={styles.card}>
            <h2>{title} &rarr;</h2>
            <h3>{author} &rarr;</h3>
            <p>{content}</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default SSGPage;
